[[plugins]]
repo = 'w0ng/vim-hybrid'
hook_add = '''
  colorscheme hybrid
  set background=dark
'''

[[plugins]]
repo = 'Yggdroot/indentLine'
hook_add = """
  let g:indentLine_color_term = 239
  let g:indentLine_char = '|'
  let g:indentLine_conceallevel = 2
"""

[[plugins]]
repo = 'airblade/vim-gitgutter'

[[plugins]]
repo = "tpope/vim-fugitive"
