[[plugins]]
repo = 'Shougo/deoplete.nvim'
hook_add = 'let g:deoplete#enable_at_startup = 1'
on_i = 1

[[plugins]]
repo = 'Shougo/deoplete-rct'
depends = 'deoplete.nvim'
on_ft = ['ruby']
on_i = 1

[[plugins]]
repo = 'mattn/emmet-vim'
on_ft = ['html', 'eruby']
on_i = 1

[[plugins]]
repo = 'tpope/vim-surround'
on_i = 1

[[plugins]]
repo = 'kchmck/vim-coffee-script'
on_ft = ['coffee']

[[plugins]]
repo = 'slim-template/vim-slim.git'
on_ft = ['slim']

[[plugins]]
repo = 'zchee/deoplete-jedi'
hook_add = 'let g:python3_host_prog = "/home/vagrant/.pyenv/versions/3.6.3/lib/python3.6/site-packages"'
on_i = 1
on_ft = ['python']

