[[plugins]]
repo = 'Shougo/deoplete.nvim'
hook_add = 'let g:deoplete#enable_at_startup = 1'
on_i = 1

[[plugins]]
repo = 'mattn/emmet-vim'
on_ft = ['html', 'eruby']
on_i = 1

[[plugins]]
repo = 'tpope/vim-surround'
on_i = 1

[[plugins]]
repo = 'kchmck/vim-coffee-script'
on_ft = ['coffee']

[[plugins]]
repo = 'slim-template/vim-slim.git'
on_ft = ['slim']

[[plugins]]
repo = 'zchee/deoplete-go'
on_ft = ['go']
on_i = 1
buid = 'make'
hook_add = '''
  let g:deoplete#sources#go#gocode_binary = "$GOPATH.'/bin/gocode'"
'''

[[plugins]]
repo = 'fatih/vim-go'
on_ft = ['go']

[[plugins]]
repo = 'zchee/deoplete-jedi'
on_ft = ['python']
on_i = 1
hook_add = '''
  let g:python3_host_prog = $PYENV_ROOT . '/shims/python'
  let g:python2_host_prog = $PYENV_ROOT . '/shims/python'
'''

[[plugins]]
repo = 'w0rp/ale'
on_ft = ['ruby']
hook_add = '''
  let g:ale_lint_on_text_changed = 'never'
  let g:ale_lint_on_enter = 0
  let g:ale_fixers = {
  \   'ruby': ['rubocop'],
  \}
  let g:ale_fix_on_save = 1
  let g:ale_completion_enabled = 1
'''

[[plugins]]
repo = 'tpope/vim-rails'
on_ft = ['ruby']
